name: PythonTestMatrix
on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  test_matrix_python:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-2019, 'macos-11', 'macos-12', macos-13, macos-14]
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        exclude:
        - os: 'ubuntu-24.04'
          version: '3.8'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          arch: x64

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: ${{ matrix.os == 'windows-2019' }}
        with:
          arch: x64

      - name: Install duckdb
        run: |
          pip install duckdb

      - name: Run minor test
        shell: bash
        run: |
          set PYTHONIOENCODING=utf-8
          echo "import duckdb" > test_extensions.py
          echo "print(duckdb.__version__)" >> test_extensions.py
          echo "duckdb.install_extension('icu')" >> test_extensions.py
          echo "duckdb.load_extension('icux')" >> test_extensions.py
          python3 test_extensions.py
